server:
  port: 9001
  connection-timeout: 2s
  keep-alive-timeout: 15s
  threads:
    max: 50
    min: 5

spring:
  main:
    banner-mode: off
  application:
    name: catalog-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

polar:
  greeting: Welcome to the local book catalog!


