server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 10
      min-spare: 5

spring:
  application:
    name: catalog-service
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: user
    password: user123
    url: jdbc:postgresql://localhost:5432/lojadb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  redis:
    connect-timeout: 2s
    host: localhost
    port: 6379
    timeout: 1s

loja:
  greeting: Bem-vindo ao catalogo de Produtos